import chalk from 'chalk';
import boxen from 'boxen';
import gradientString from 'gradient-string';
import { marked } from 'marked';
import { markedTerminal } from 'marked-terminal';
import type { Provider, CostClass } from '../providers/types.js';
import { classifyProvider } from '../providers/index.js';
import type { Session } from '../storage/sessions.js';

marked.use(markedTerminal() as Parameters<typeof marked.use>[0]);

// Cude Code brand mark: hexagon opened on the right (forming a "C"), a ">"
// chevron inside, and the split notch at the bottom vertex — the same geometry
// as assets/cude-mark.svg. Generated by tools/generate-logo.mjs into half-blocks.
const LOGO_ART =
  '             ▗▄███▄▖\n' +
  '          ▄▟█████████▙▄\n' +
  '      ▗▄█████▀▘   ▝▀█████▄▖\n' +
  '   ▄▟████▛▀           ▀▜████▙▄\n' +
  '  ████▀▘                 ▝▀████\n' +
  '  ███      ▐█▙▄              ▀\n' +
  '  ███      ▝▀███▙▄\n' +
  '  ███         ▝▀███▙▄\n' +
  '  ███           ▄████\n' +
  '  ███        ▄▟███▀▘\n' +
  '  ███      ▐███▀▘\n' +
  '  ███▄      ▀▘             ▄▟█▄\n' +
  '  ▀█████▄▖             ▗▄█████▀\n' +
  '     ▀▜████▄▄       ▄▄████▛▀\n' +
  '        ▝▀████▙▄ ▄▟████▀▘\n' +
  '           ▝▀███ ███▀▘\n' +
  '             ▜█▛ ▜█▛';

export function showBanner(): void {
  const gradient = gradientString('#ffffff', '#c7d2fe', '#6366f1');
  console.log(gradient(LOGO_ART));
  console.log();
  console.log(
    '  ' +
    chalk.white.bold('CUDE CODE') +
    chalk.dim('  v0.1.0')
  );
  console.log(
    '  ' +
    chalk.dim('YAZ. ANLA. ') + chalk.hex('#6366f1')('ÜRET.')
  );
  console.log(chalk.dim('  19 providers · 22 tools · 9 task types · browser · RAG'));
  console.log();
}

export function renderMarkdown(text: string): string {
  try {
    const result = marked(text);
    return typeof result === 'string' ? result : text;
  } catch {
    return text;
  }
}

export function showCostInfo(cost: number, inputTokens: number, outputTokens: number): void {
  if (cost === 0) {
    console.log(chalk.dim(`  [Free · ${inputTokens} in / ${outputTokens} out tokens]`));
  } else {
    console.log(
      chalk.dim(`  [$${cost.toFixed(6)} · ${inputTokens} in / ${outputTokens} out tokens]`)
    );
  }
}

export function showError(message: string): void {
  console.error(
    boxen(chalk.red(message), {
      padding: 1,
      borderColor: 'red',
      borderStyle: 'round',
      title: chalk.red('Error'),
      titleAlignment: 'left',
    })
  );
}

export function showWarning(message: string): void {
  console.warn(
    boxen(chalk.yellow(message), {
      padding: { top: 0, bottom: 0, left: 1, right: 1 },
      borderColor: 'yellow',
      borderStyle: 'round',
      title: chalk.yellow('Warning'),
      titleAlignment: 'left',
    })
  );
}

export function showSuccess(message: string): void {
  console.log(
    boxen(chalk.green(message), {
      padding: { top: 0, bottom: 0, left: 1, right: 1 },
      borderColor: 'green',
      borderStyle: 'round',
      title: chalk.green('Success'),
      titleAlignment: 'left',
    })
  );
}

export function showInfo(message: string): void {
  console.log(chalk.cyan('  ℹ ') + message);
}

/** Reads the provider's own declared cost class — never a name lookup. */
function costLabel(cost: CostClass): string {
  switch (cost) {
    case 'local': return chalk.cyan('Local');
    case 'free': return chalk.green('Free');
    case 'mixed': return chalk.green('Free/Paid');
    default: return chalk.dim('Paid');
  }
}

export function showProviderTable(providers: Array<{ provider: Provider; available: boolean }>): void {
  const nameWidth = 22;
  const statusWidth = 14;
  const freeWidth = 8;

  const header =
    chalk.bold.cyan('Provider'.padEnd(nameWidth)) +
    chalk.bold.cyan('Status'.padEnd(statusWidth)) +
    chalk.bold.cyan('Free/Local');

  console.log();
  console.log(header);
  console.log(chalk.dim('─'.repeat(nameWidth + statusWidth + freeWidth)));

  for (const { provider, available } of providers) {
    const name = provider.displayName.padEnd(nameWidth);
    let status: string;
    if (provider.isConfigured()) {
      status = available ? chalk.green('✓ Available').padEnd(statusWidth + 9) : chalk.yellow('⚠ Unreachable').padEnd(statusWidth + 9);
    } else if (provider.name === 'ollama') {
      status = available ? chalk.green('✓ Running').padEnd(statusWidth + 9) : chalk.dim('○ Not running').padEnd(statusWidth + 9);
    } else {
      status = chalk.dim('○ Not configured').padEnd(statusWidth + 9);
    }
    console.log(chalk.white(name) + status + costLabel(classifyProvider(provider)));
  }
  console.log();
}

export function showSessionTable(sessions: Session[]): void {
  if (sessions.length === 0) {
    console.log(chalk.dim('  No sessions found.'));
    return;
  }

  const idWidth = 10;
  const nameWidth = 24;
  const providerWidth = 14;
  const dateWidth = 20;
  const costWidth = 12;

  const header =
    chalk.bold.cyan('ID'.padEnd(idWidth)) +
    chalk.bold.cyan('Name'.padEnd(nameWidth)) +
    chalk.bold.cyan('Provider'.padEnd(providerWidth)) +
    chalk.bold.cyan('Updated'.padEnd(dateWidth)) +
    chalk.bold.cyan('Cost');

  console.log();
  console.log(header);
  console.log(chalk.dim('─'.repeat(idWidth + nameWidth + providerWidth + dateWidth + costWidth)));

  for (const session of sessions) {
    const shortId = session.id.split('-')[0];
    const name = session.name.substring(0, nameWidth - 2).padEnd(nameWidth);
    const provider = session.provider.padEnd(providerWidth);
    const date = new Date(session.updatedAt).toLocaleDateString('en-US', {
      month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'
    }).padEnd(dateWidth);
    const cost = session.totalCost === 0 ? chalk.green('Free') : chalk.yellow(`$${session.totalCost.toFixed(4)}`);

    console.log(
      chalk.dim(shortId.padEnd(idWidth)) +
      chalk.white(name) +
      chalk.cyan(provider) +
      chalk.dim(date) +
      cost
    );
  }
  console.log();
}

export function showModelTable(
  models: Array<{ id: string; name: string; provider: string; free: boolean; local: boolean; pricing?: { inputPerMillion: number; outputPerMillion: number } }>
): void {
  console.log();
  console.log(chalk.bold.cyan('Available Models'));
  console.log(chalk.dim('─'.repeat(80)));

  const byProvider: Record<string, typeof models> = {};
  for (const m of models) {
    if (!byProvider[m.provider]) byProvider[m.provider] = [];
    byProvider[m.provider].push(m);
  }

  for (const [provider, providerModels] of Object.entries(byProvider)) {
    console.log(chalk.bold.white(`\n  ${provider.toUpperCase()}`));
    for (const m of providerModels) {
      const badge = m.local
        ? chalk.cyan('[local]')
        : m.free
        ? chalk.green('[free]')
        : chalk.dim('[paid]');
      const pricing = m.pricing
        ? chalk.dim(` $${m.pricing.inputPerMillion}/$${m.pricing.outputPerMillion} per M tokens`)
        : '';
      console.log(`    ${chalk.white(m.id.padEnd(35))} ${badge}${pricing}`);
    }
  }
  console.log();
}

export function printKeyValue(key: string, value: string, color: 'green' | 'yellow' | 'cyan' | 'white' = 'white'): void {
  console.log(chalk.dim(`  ${key.padEnd(22)}: `) + chalk[color](value));
}

export function printSeparator(char = '─', width = 60): void {
  console.log(chalk.dim(char.repeat(width)));
}

export function formatCost(cost: number): string {
  if (cost === 0) return chalk.green('Free');
  if (cost < 0.001) return chalk.yellow(`$${(cost * 1000).toFixed(4)}m`);
  return chalk.yellow(`$${cost.toFixed(6)}`);
}

export function showQuickTips(): void {
  console.log();
  console.log(chalk.bold.cyan('Quick Tips:'));
  console.log(chalk.dim('  • Start with: cude chat --free    # Use free providers'));
  console.log(chalk.dim('  • Customize:  cude config setup   # Configure API keys'));
  console.log(chalk.dim('  • Run tasks:  cude run "prompt"   # Use autonomous agent'));
  console.log(chalk.dim('  • View help:  cude --help         # See all commands'));
  console.log();
}

export function showGettingStarted(): void {
  console.log();
  console.log(chalk.bold.cyan('Getting Started:'));
  console.log();
  console.log(chalk.white('1. Configure API Keys:'));
  console.log(chalk.cyan('   cude setup'));
  console.log();
  console.log(chalk.white('2. Choose a Provider:'));
  console.log(chalk.cyan('   cude providers list'));
  console.log();
  console.log(chalk.white('3. Start Chatting:'));
  console.log(chalk.cyan('   cude chat'));
  console.log();
  console.log(chalk.white('4. Run Autonomous Agent:'));
  console.log(chalk.cyan('   cude run "Create a TypeScript server"'));
  console.log();
}

export function showSpinner(message: string): void {
  console.log(chalk.cyan('⠋ ') + message);
}

export function showStep(step: number, total: number, message: string): void {
  const progress = chalk.cyan(`[${step}/${total}]`);
  console.log(progress + ' ' + message);
}

export function showTable(headers: string[], rows: string[][], colors?: string[]): void {
  const columnWidths = headers.map((h, i) =>
    Math.max(h.length, Math.max(...rows.map(r => r[i]?.length ?? 0)))
  );

  const headerRow = headers.map((h, i) => h.padEnd(columnWidths[i])).join('  ');
  console.log(chalk.bold.cyan(headerRow));
  console.log(chalk.dim('─'.repeat(columnWidths.reduce((a, w) => a + w + 2, 0))));

  for (const row of rows) {
    const formattedRow = row.map((cell, i) => {
      const padded = cell.padEnd(columnWidths[i]);
      const color = colors?.[i];
      if (!color) return padded;

      switch (color) {
        case 'cyan': return chalk.cyan(padded);
        case 'green': return chalk.green(padded);
        case 'yellow': return chalk.yellow(padded);
        case 'red': return chalk.red(padded);
        case 'blue': return chalk.blue(padded);
        case 'magenta': return chalk.magenta(padded);
        case 'gray': return chalk.gray(padded);
        case 'dim': return chalk.dim(padded);
        case 'bold': return chalk.bold(padded);
        default: return padded;
      }
    }).join('  ');
    console.log(formattedRow);
  }
  console.log();
}

export function showConfigured(items: string[]): void {
  console.log(chalk.green('✓ Configured:') + ' ' + items.join(', '));
}

export function showNotConfigured(items: string[]): void {
  console.log(chalk.yellow('⚠ Not configured:') + ' ' + items.join(', '));
}

export function showProgress(current: number, total: number, message?: string): void {
  const percent = Math.round((current / total) * 100);
  const filled = Math.round((percent / 10));
  const empty = 10 - filled;
  const bar = chalk.cyan('█'.repeat(filled)) + chalk.dim('░'.repeat(empty));
  const text = message ? ` ${message}` : '';
  console.log(`${bar} ${percent}%${text}`);
}

export function showCommand(command: string, description?: string): void {
  console.log(chalk.cyan('  $') + ' ' + chalk.white(command));
  if (description) {
    console.log(chalk.dim('    ' + description));
  }
}

export function showList(items: string[], bullet = '•'): void {
  for (const item of items) {
    console.log(chalk.dim(`  ${bullet} `) + item);
  }
}

export function showKeyValue(key: string, value: string, width = 24): void {
  console.log(chalk.white(key.padEnd(width)) + ': ' + chalk.cyan(value));
}
